spring:
  application:
    name: dummy-adapter

server:
  port: ${PORT:8020}
  context-path: /${spring.application.name}/

eureka:
  instance:
    metadata-map:
      instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    service-url:
      default-zone: http://localhost:8761/service-registry/eureka/

logging:
  level:
    com.netflix: INFO
  file: ${user.home}/asg/logs/${spring.application.name}-${server.port}.log
