server:
  port: ${PORT:8080}
  context-path: /gateway-demo/

zuul:
  ignored-services: '*'
  routes:
    tcm-demo:
      path: /tcm-demo/**
      service-id: tcm-demo
      stripPrefix: false

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

logging:
  level:
    com.netflix: DEBUG