server:
  port: ${PORT:8070}
  context-path: /repository-adapter-demo/

eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

logging:
  level:
    com.netflix: DEBUG