spring:
  application:
    name: gateway
  jmx:
    enabled: false

server:
  port: ${PORT:8080}
  context-path: /${spring.application.name}/

zuul:
  ignored-services: '*'
  routes:
    tcm-demo:
      path: /dummy-tcm/**
      service-id: dummy-tcm
      stripPrefix: false

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/service-registry/eureka/

logging:
  level:
    com.netflix: INFO
  file: ${user.home}/asg/logs/${spring.application.name}-${server.port}.log