spring:
  application:
    name: gateway

server:
  port: ${PORT:8080}
  context-path: /${spring.application.name}/

zuul:
  ignored-services: '*'
  routes:
    tcm-demo:
      path: /dummy-tcm/**
      service-id: dummy-tcm
      stripPrefix: false

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/service-registry/eureka/

logging:
  level:
    com.netflix: DEBUG