server:
  port: ${PORT:8050}
  context-path: /configuration-demo/

eureka:
  instance:
    preferIpAddress: false
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

logging:
  level:
    com.netflix: DEBUG
