server:
  port: ${PORT:5050}
  context-path: /service-repository-demo/

eureka:
  instance:
    statuspage-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    com.netflix: DEBUG
  file: C:/eureka.log
